stages:
  {{ stage_name }}:
    params:
      - dso.quarto
    deps:
      - src/{{ stage_name }}.ipynb
    outs:
      - output
      - report/{{ stage_name }}.html
    cmd:
      - uv run dso exec quarto .
