name: Publish DSO to PyPI
on:
  release:
    types: [published]

jobs:
  release:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dso

    steps:
      - uses: actions/checkout@v4
        name: Check out source-code repository

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          pip install .

      - name: Build the distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
