name: "DSO lint"
on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre_commit:
    name: "pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - uses: pre-commit/action@v2.0.3
