name: Docs screenshots
on:
  workflow_dispatch:

jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out DSO code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install DSO
        run: pip install .

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          clean_img_paths: docs/images/screenshots/*.svg
          commit_changes: "true"
          skip_git_checks: "true"
